_commit: v2
_src_path: https://github.com/kitware-resonant/resonant-meta-template
django_project: true
max_python_minor_version: 13
min_python_minor_version: 13
project_slug: '{{ project_slug }}'
python_package_name: '{{ python_package_name }}'

#copier updated