services:
  postgres:
    image: postgres:18
    shm_size: 128mb
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "postgres"]
      start_period: 30s
      start_interval: 2s
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      start_period: 30s
      start_interval: 2s
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  seaweedfs:
    image: chrislusf/seaweedfs:4.47
    environment:
      AWS_ACCESS_KEY_ID: seaweedAccessKey
      AWS_SECRET_ACCESS_KEY: seaweedSecretKey
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8333/healthz"]
      start_period: 30s
      start_interval: 2s
    ports:
      - 8333:8333
      - 23646:23646
    volumes:
      - seaweedfs:/data

volumes:
  postgres:
  rabbitmq:
  seaweedfs:
