release: ./manage.py migrate
web: daphne -b 0.0.0.0 -p $PORT {{ cookiecutter.pkg_name }}.asgi:application
worker: REMAP_SIGTERM=SIGQUIT celery --app {{ cookiecutter.pkg_name }}.celery worker --loglevel INFO --without-heartbeat
