release: ./manage.py migrate
web: gunicorn --bind 0.0.0.0:$PORT {{ cookiecutter.pkg_name }}.wsgi
worker: REMAP_SIGTERM=SIGQUIT celery worker --app {{ cookiecutter.pkg_name }}.celery --loglevel info --without-heartbeat
