name: ci
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  test-resonant-settings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          working-directory: django-resonant-settings
      - name: Run tests
        run: |
          uv run tox
        working-directory: django-resonant-settings
  test-cookecutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cookiecutter-variables: ["include_example_code=yes", "include_example_code=no"]
    services:
      postgres:
        # Postgres depends on the OS locale for collation.
        # Alpine provides locales differently, so for better dev-prod parity, don't use it.
        image: postgres:latest
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready --username postgres"
          --health-start-period 30s
          --health-start-interval 2s
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:management-alpine
        options: >-
          --health-cmd "rabbitmq-diagnostics ping"
          --health-start-period 30s
          --health-start-interval 2s
        ports:
          - 5672:5672
      minio:
        # This image does not require any command arguments (which GitHub Actions don't support)
        image: bitnami/minio:2025.4.22
        env:
          MINIO_ROOT_USER: minioAccessKey
          MINIO_ROOT_PASSWORD: minioSecretKey
        options: >-
          --health-cmd "mc ready local"
          --health-timeout 1s
          --health-start-period 30s
          --health-start-interval 2s
        ports:
          - 9000:9000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # There's no lockfile at this point
          enable-cache: false
      - name: Eject from cookiecutter
        run: |
          uvx cookiecutter --no-input . project_name=Resonant ${{ matrix.cookiecutter-variables }}
      - name: Add local django-resonant-settings
        run: |
          uv add ../django-resonant-settings[allauth]
        working-directory: resonant
      - name: Run tox tests from new project
        run: |
          uv run tox
        env:
          DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
          DJANGO_CELERY_BROKER_URL: amqp://localhost:5672/
          DJANGO_MINIO_STORAGE_URL: http://minioAccessKey:minioSecretKey@localhost:9000/django-storage-testing
        working-directory: resonant
