name: release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Build the Python distribution
        run: |
          uv build
        working-directory: django-resonant-settings
      - name: Publish the Python distributions to PyPI
        run: |
          uv publish --trusted-publishing=always
        working-directory: django-resonant-settings
