[tox]
min_version = 4.22
requires =
    tox-uv
env_list =
    lint
    type

[testenv]
runner = uv-venv-lock-runner
extras =
    allauth
    celery

[testenv:lint]
package = skip
dependency_groups =
    lint
commands =
    flake8 .

[testenv:format]
package = skip
dependency_groups =
    format
commands =
    isort .
    black .

[testenv:type]
dependency_groups =
    type
commands =
    mypy {posargs}

[flake8]
max-line-length = 100
show-source = True
extend-exclude =
    .venv/,
ignore =
    # closing bracket does not match indentation of opening bracket's line
    E123,
    # whitespace before ':'
    E203,
    # line break before binary operator
    W503,
    # Missing docstring in *
    D10,
per-file-ignores =
    # 1 blank line required between summary line and description
    # First line should end with a period
    resonant_settings/*:D205,D400
